drop table clienti_banca;
drop table cutie_valori;
drop table investitii;
drop table grad_indatorare;
drop table angajati_banca;
drop table imprumuturi;
drop table clienti_banca;
CREATE TABLE clienti_banca (
id_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
nume_client VARCHAR2(100),
data_infiintare_cont DATE, 
sold_cont NUMBER, 
IBAN VARCHAR2(34) 
);

CREATE TABLE imprumuturi (
id_imprumut NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
id_client NUMBER REFERENCES clienti_banca(id_client),
moneda_imprumut VARCHAR2(10),
valoare_imprumut NUMBER, 
valoare_sold NUMBER, 
dobanda NUMBER(5, 2) 
);

CREATE TABLE angajati_banca (
id_angajat NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nume_angajat VARCHAR2(100), 
pozitie_ocupata VARCHAR2(50), 
salariu NUMBER, 
este_client VARCHAR2(3) CHECK (este_client IN ('Da', 'Nu')), 
id_client NUMBER DEFAULT 0 
);

CREATE TABLE grad_indatorare (
id_client NUMBER REFERENCES clienti_banca(id_client), 
valoare_indatorare NUMBER, 
nota NUMBER CHECK (nota BETWEEN 1 AND 10), 
CONSTRAINT chk_valoare_indatorare_nota CHECK (
(valoare_indatorare >= 1 AND valoare_indatorare < 2000 AND nota = 1) OR
(valoare_indatorare >= 2000 AND valoare_indatorare < 4000 AND nota = 2) OR
(valoare_indatorare >= 4000 AND valoare_indatorare < 6000 AND nota = 3) OR
(valoare_indatorare >= 6000 AND valoare_indatorare < 8000 AND nota = 4) OR
(valoare_indatorare >= 8000 AND valoare_indatorare < 10000 AND nota = 5) OR
(valoare_indatorare >= 10000 AND valoare_indatorare < 12000 AND nota = 6) OR
(valoare_indatorare >= 12000 AND valoare_indatorare < 14000 AND nota = 7) OR
(valoare_indatorare >= 14000 AND valoare_indatorare < 16000 AND nota = 8) OR
(valoare_indatorare >= 16000 AND valoare_indatorare < 18000 AND nota = 9) OR
(valoare_indatorare >= 18000 AND nota = 10)
    )
);


CREATE TABLE investitii (
id_investitie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
id_responsabil NUMBER, 
denumire_investitie VARCHAR2(255),
eticheta_bursa VARCHAR2(50), 
valoare_profit NUMBER(5, 2), 
suma_investita NUMBER, 
numar_actiuni NUMBER, 
valoare_per_actiune NUMBER, 

  
CONSTRAINT fk_responsabil FOREIGN KEY (id_responsabil) REFERENCES angajati_banca(id_angajat),
    
CONSTRAINT chk_valoare_per_actiune CHECK (
numar_actiuni > 0 AND valoare_per_actiune = suma_investita / numar_actiuni
    )
);




CREATE TABLE cutie_valori (
id_cutie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
id_client NUMBER, 
tip_cutie NUMBER(1) CHECK (tip_cutie IN (1, 2, 3)), 
valoare_declarata NUMBER, 
scurta_descriere VARCHAR2(100), 
CONSTRAINT fk_id_client FOREIGN KEY (id_client) REFERENCES clienti_banca(id_client)
);



--POPULARE TABELA CLIENTI_BANCA
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN)
VALUES ('Rares Erculescu', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 5000, 'RO00AAAA0000000000000');
SELECT * FROM clienti_banca;
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN)
VALUES ('Ion Ionescu', TO_DATE('2020-11-25', 'YYYY-MM-DD'), 200, 'RO01AAAA0000000000000');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN)
VALUES ('Ana Andreea', TO_DATE('2019-08-28', 'YYYY-MM-DD'), 15000, 'RO00AAAA0000000960000');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN)
VALUES ('Carmen Braticevici', TO_DATE('2024-08-21', 'YYYY-MM-DD'), 2420, 'RO00AAAA0000000000223');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN)
VALUES ('Isabelle Andreea', TO_DATE('2012-03-18', 'YYYY-MM-DD'), 590, 'RO00AAAA0000000003023');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Eva Maria', TO_DATE('2015-04-05', 'YYYY-MM-DD'), 9200, 'RO00AAAA0000000003773');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Delia Andreea', TO_DATE('2021-05-27', 'YYYY-MM-DD'), 12000, 'US00AAAA0000000003693');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Luca Montezemollo', TO_DATE('2009-06-11', 'YYYY-MM-DD'), 37000, 'IT00AAAA0000000003214');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Nicusor Dan', TO_DATE('2005-02-26', 'YYYY-MM-DD'), 9000, 'FR00AAAA0000000053023');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Ingrid Winkler', TO_DATE('2017-06-28', 'YYYY-MM-DD'), 72590, 'DE00AAAA0000000003023');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Andrei Tatulescu', TO_DATE('2019-10-02', 'YYYY-MM-DD'), 100090, 'RO00AAAA0000000007733');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Maria Tudor', TO_DATE('2015-06-02', 'YYYY-MM-DD'), 5900, 'RO00AAAB00023000007733');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Daniel Mihai', TO_DATE('2023-09-30', 'YYYY-MM-DD'), 300090, 'RO00AAAA0000000005733');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Celestin Dumitru', TO_DATE('2018-09-12', 'YYYY-MM-DD'), 8090, 'RO00AAAA0000000127733');
INSERT INTO clienti_banca (nume_client, data_infiintare_cont, sold_cont, IBAN) 
VALUES ('Narcis Popescu', TO_DATE('2020-12-06', 'YYYY-MM-DD'), 900090, 'RO00AAAA00021540007733');
SELECT*FROM clienti_banca;


--POPULARE TABELA IMPRUMUTURI
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (1, 'EUR', 10000, 8000, 5.50);
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (3, 'RON', 6000, 400, 2.50);
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (9, 'EUR', 100000, 6566, 3.25);
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (4, 'RON', 2000, 800, 15.50);
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (2, 'USD', 900, 150, 4.20);
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (6, 'CHF', 600, 20, 1.50);
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (10, 'RON', 100000, 7250, 2.90);
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (11, 'EUR', 100000, 8000, 3.00);
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (12, 'RON', 15000, 8000, 7.50);
INSERT INTO imprumuturi (id_client, moneda_imprumut, valoare_imprumut, valoare_sold, dobanda)
VALUES (7, 'RON', 6000, 1000, 2.50);
SELECT* FROM imprumuturi;

--POPULARE TABELA ANGAJATI_BANCA
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Narcis Popescu', 'Manager Investitii', 9000, 'Da', 15);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Daniel Mihai', 'Director Sucursala', 17000, 'Da', 13);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Horia Ivanovici', 'Casier', 7000, 'Nu', 0);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Nicusor Dan', 'Agent Paza', 5000, 'Da', 9);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Andrei Mihai', 'Broker Credite', 10000, 'Nu', 0);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Ioana Popescu', 'Casier', 7050, 'Nu', 0);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Toma Magelan', 'Broker Credite', 9000, 'Nu', 0);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Andrei Puscasu', 'Manager Mentenanta', 7200, 'Nu', 0);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Andrei Tatulescu', 'Manager Operational', 12000, 'Da', 11);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Ion Ionescu', 'Manager HR', 6000, 'Da', 2);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Razvan Stanciu', 'Coordonator Credite', 9300, 'Nu', 0);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Gigel Gigelovici', 'Reprezentant PR', 5000, 'Nu', 0);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Vasile Bojog', 'Manager PR', 9066, 'Nu', 0);
INSERT INTO angajati_banca (nume_angajat, pozitie_ocupata, salariu, este_client, id_client)
VALUES ('Florin Iubu', 'Director General', 20000, 'Nu', 0);
SELECT* FROM angajati_banca;

--POPULARE TABELA GRAD_INDATORARE
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (1, 8000, 5);
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (2, 150, 1);
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (3, 400, 1);
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (4, 800, 1);
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (5, 20, 1);
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (6, 1000, 1);
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (8, 6566, 4);
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (9, 7250, 4);
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (10, 8000, 5);
INSERT INTO grad_indatorare (id_client, valoare_indatorare, nota)
VALUES (11, 8000, 5);
SELECT* FROM grad_indatorare;


--POPULARE TABELA INVESTITII
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, '3M', 'NASDAQ:MMM', 12.50, 50000, 500, 100
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'ACCENTURE', 'NASDAQ:ACC', 2.50, 20000, 500, 40
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'NVIDIA', 'NASDAQ:NVDA', 18.00, 150000, 100, 1500
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'TESLA', 'NASDAQ:TSLA', 7.20, 90000, 128, 703.125
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'ORACLE CORPORATION', 'NASDAQ:ORCL', -1.50, 10000, 100, 100
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'PROCTER AND GAMBLE', 'NASDAQ:PG', 2.50, 11000, 2000, 5.5
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'RAYTHEON COMPANY', 'NASDAQ:RTN', 5.50, 42000, 2100, 20
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'LOCKHEED MARTIN', 'NASDAQ:LMT', 7.30, 69000, 750, 92
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'BOEING', 'NASDAQ:BA', -0.30, 10000, 80, 125
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'CISCO', 'NASDAQ:CSCO', 0.70, 80000, 400, 200
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'CORTEVA', 'NASDAQ:CTVA', 2.10, 10000, 625, 16
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'DELL TECHNOLOGIES', 'NASDAQ:DELL', 5.10, 90000, 900, 100
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'GARMIN', 'NASDAQ:GRMN', 1.90, 32000, 128, 250
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'SOCIETATEA ELECTRICA', 'BVB:EL', 0.90, 10000, 100, 100
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
INSERT INTO investitii (id_responsabil, denumire_investitie, eticheta_bursa, valoare_profit, suma_investita, numar_actiuni, valoare_per_actiune)
SELECT id_angajat, 'VOLKSVAGEN GROUP', 'FRA:VOW3', -0.90, 20000, 400, 50
FROM angajati_banca
WHERE pozitie_ocupata = 'Manager Investitii';
SELECT* FROM investitii;

--POPULAT TABELA CUTIE_VALORI
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (1, 1, 15000, 'Documente Importante');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (15, 3, 50000, 'Ceasuri, documente');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (13, 2, 22000, 'Bijuterii');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (11, 1, 15000, 'Documente Importante');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (10, 3, 22000, 'Titluri de Stat');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (8, 2, 25000, 'Bijuterii');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (3, 1, 9000, 'Ceasuri');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (9, 1, 70000, 'Titluri de Stat');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (14, 3, 65000, 'Picturi');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (4, 2, 90000, 'Bijuterii');
INSERT INTO cutie_valori (id_client, tip_cutie, valoare_declarata, scurta_descriere)
VALUES (2, 1, 150000, 'Documente Importante');
SELECT* FROM cutie_valori;


--ACTUALIZAREA INREGISTRARILOR
UPDATE investitii
SET denumire_investitie='CORTEVA DUPONT',
valoare_profit=3.1
WHERE id_investitie=11;
SELECT* FROM investitii;

UPDATE cutie_valori
SET valoare_declarata=0,
scurta_descriere='Nedeclarat'
WHERE id_cutie=7;
SELECT* FROM CUTIE_VALORI;

UPDATE ANGAJATI_BANCA
SET NUME_ANGAJAT='Ioana Mihai',
SALARIU=8600,
POZITIE_OCUPATA='Casier Sef'
WHERE ID_ANGAJAT=6;
SELECT*FROM ANGAJATI_BANCA;

UPDATE IMPRUMUTURI
SET VALOARE_SOLD=0
WHERE ID_IMPRUMUT=6;
SELECT* FROM IMPRUMUTURI;

DELETE FROM GRAD_INDATORARE
WHERE ID_CLIENT=5;
SELECT* FROM GRAD_INDATORARE;

UPDATE CLIENTI_BANCA
SET SOLD_CONT=25000
WHERE ID_CLIENT=5;
SELECT*FROM CLIENTI_BANCA;



--STERGEREA SI RECUPERAREA UNEI TABELE
DROP TABLE CUTIE_VALORI;
SELECT *FROM CUTIE_VALORI;
FLASHBACK TABLE CUTIE_VALORI TO BEFORE DROP;


--UTILIZAREA COMENZILOR UNION, INTERSECT SI MINUS
SELECT ID_CLIENT
FROM IMPRUMUTURI
UNION SELECT ID_CLIENT 
FROM CUTIE_VALORI;


SELECT ID_CLIENT
FROM CLIENTI_BANCA
INTERSECT SELECT ID_CLIENT
FROM ANGAJATI_BANCA;

SELECT ID_CLIENT
FROM CLIENTI_BANCA
MINUS SELECT ID_CLIENT
FROM ANGAJATI_BANCA;

SELECT ID_CLIENT,NUME_CLIENT
FROM CLIENTI_BANCA
MINUS SELECT ID_CLIENT,NUME_ANGAJAT
FROM ANGAJATI_BANCA;

--UTILIZAREA EXPRESIILOR DECODE, CASE SI FUNCTIILE SINGLE-ROW,DE GRUP,JONCTIUNI,CERERI IMBRICATE
SELECT ID_CLIENT,VALOARE_INDATORARE,
DECODE( NOTA,1,'FOARTE MICA',2,'MICA',3,'MODERATA',4,'RIDICATA',5,'EXTREM DE RIDICATA','DE CE MAI INCERCI?')
AS NIVEL_INDATORARE FROM GRAD_INDATORARE;

SELECT*FROM ANGAJATI_BANCA;
SELECT 
ID_ANGAJAT,NUME_ANGAJAT,SALARIU, CASE
WHEN SALARIU<5001 THEN 'VENITURI MICI'
WHEN SALARIU BETWEEN 5001 AND 9001 THEN 'VENITURI MEDII'
WHEN SALARIU >9001 THEN 'VENITURI MARI'
ELSE 'NECUNOSCUT'
END AS CATEGORIE_VENITURI
FROM ANGAJATI_BANCA;

SELECT 
DECODE(este_client, 'Da', 'Client', 'Nu', 'Non-Client') AS STATUS_CLIENT,
COUNT(*) AS TOTAL_ANGAJATI
FROM angajati_banca
GROUP BY DECODE(este_client, 'Da', 'Client', 'Nu', 'Non-Client');


SELECT* FROM INVESTITII;

UPDATE INVESTITII
SET VALOARE_PROFIT=
CASE WHEN VALOARE_PROFIT<0 THEN VALOARE_PROFIT-1
WHEN VALOARE_PROFIT>0 THEN VALOARE_PROFIT+0.25
ELSE VALOARE_PROFIT
END;

SELECT 
id_client,
nume_client,
CASE
WHEN sold_cont < 1000 THEN 
CASE 
WHEN data_infiintare_cont < TO_DATE('2020-01-01', 'YYYY-MM-DD') THEN 'CONT VECHI SI SOLD SCAZUT'
ELSE 'CONT NOU SI SOLD SCAZUT'
END
WHEN sold_cont >= 10000 THEN 'CONT CU SOLD RIDICAT'
ELSE 'CONT ACTIV'
END AS STARE_CONT
FROM clienti_banca;

SELECT*FROM CUTIE_VALORI
ORDER BY SCURTA_DESCRIERE;
SELECT
ID_CLIENT,VALOARE_DECLARATA,
CASE
WHEN VALOARE_DECLARATA > 50000 THEN
CASE
WHEN SCURTA_DESCRIERE LIKE 'DOCUM%' THEN 'DOCUMENTE CU VALOARE RIDICATA'
WHEN SCURTA_DESCRIERE LIKE 'BIJ%' THEN 'BIJUTERII CU VALOARE RIDICATA'
WHEN SCURTA_DESCRIERE LIKE 'PIC%' THEN 'PICTURI CU VALOARE RIDICATA'
WHEN SCURTA_DESCRIERE LIKE 'CEAS%' THEN 'CEASURI CU VALOARE RIDICATA'
ELSE 'VALOARE RIDICATA' END
WHEN VALOARE_DECLARATA=0 THEN 'VALOARE NEDECLARATA'
WHEN VALOARE_DECLARATA<=50000 THEN 'VALOARE SCAZUTA' 
END AS CLASIFICARE_CUTII
FROM CUTIE_VALORI
ORDER BY SCURTA_DESCRIERE;

SELECT*FROM IMPRUMUTURI;

SELECT ID_CLIENT,NUME_CLIENT FROM
CLIENTI_BANCA WHERE ID_CLIENT IN(SELECT ID_CLIENT FROM IMPRUMUTURI
WHERE VALOARE_IMPRUMUT>6000);

SELECT ID_CLIENT , TO_CHAR(DATA_INFIINTARE_CONT,'DD-MM-YYYY')AS DATA_INF,
UPPER(NUME_CLIENT) AS NUME_CAPS
FROM CLIENTI_BANCA;

SELECT*FROM INVESTITII;
SELECT 
AVG(SUMA_INVESTITA) AS INVESTIT_PER_COMPANIE,
SUM(SUMA_INVESTITA)AS TOTAL_INVESTIT
FROM INVESTITII
WHERE ETICHETA_BURSA LIKE 'NAS%';

SELECT C.ID_CLIENT,C.NUME_CLIENT,I.ID_IMPRUMUT,I.VALOARE_IMPRUMUT FROM
CLIENTI_BANCA C JOIN
IMPRUMUTURI I ON C.ID_CLIENT=I.ID_CLIENT;

SELECT C.ID_CLIENT,C.NUME_CLIENT,A.SALARIU FROM
CLIENTI_BANCA C JOIN
ANGAJATI_BANCA A ON C.ID_CLIENT=A.ID_CLIENT;

SELECT 
C.ID_CLIENT,
C.NUME_CLIENT,
C.DATA_INFIINTARE_CONT,
C.SOLD_CONT,
C.IBAN,
I.ID_IMPRUMUT,
I.MONEDA_IMPRUMUT,
I.VALOARE_IMPRUMUT,
I.VALOARE_SOLD,
I.DOBANDA
FROM CLIENTI_BANCA C
LEFT JOIN IMPRUMUTURI I ON C.ID_CLIENT = I.ID_CLIENT;

SELECT 
C.ID_CLIENT,
C.NUME_CLIENT,
C.DATA_INFIINTARE_CONT,
C.SOLD_CONT,
C.IBAN,
I.ID_IMPRUMUT,
I.MONEDA_IMPRUMUT,
I.VALOARE_IMPRUMUT,
I.VALOARE_SOLD,
I.DOBANDA,
V.ID_CUTIE,
V.TIP_CUTIE,
V.VALOARE_DECLARATA,
V.SCURTA_DESCRIERE
FROM CLIENTI_BANCA C
LEFT JOIN IMPRUMUTURI I ON C.ID_CLIENT=I.ID_CLIENT
LEFT JOIN CUTIE_VALORI V ON C.ID_CLIENT=V.ID_CLIENT;


SELECT 
c.ID_CLIENT,
c.NUME_CLIENT,
c.DATA_INFIINTARE_CONT,
c.SOLD_CONT,
c.IBAN,
G.VALOARE_INDATORARE,
G.NOTA
FROM CLIENTI_BANCA c
LEFT JOIN GRAD_INDATORARE G ON C.ID_CLIENT = G.ID_CLIENT;


SELECT 
I.ID_IMPRUMUT,
I.ID_CLIENT,
I.MONEDA_IMPRUMUT,
I.VALOARE_IMPRUMUT,
I.VALOARE_SOLD,
I.DOBANDA,
G.VALOARE_INDATORARE,
G.NOTA
FROM IMPRUMUTURI I
LEFT JOIN GRAD_INDATORARE G ON I.ID_CLIENT=G.ID_CLIENT;

SELECT 
C.NUME_CLIENT,
C.DATA_INFIINTARE_CONT,
C.SOLD_CONT,
C.IBAN,
I.ID_IMPRUMUT,
I.ID_CLIENT,
I.MONEDA_IMPRUMUT,
I.VALOARE_IMPRUMUT,
I.VALOARE_SOLD,
I.DOBANDA,
G.VALOARE_INDATORARE,
G.NOTA
FROM IMPRUMUTURI I
LEFT JOIN GRAD_INDATORARE G ON I.ID_CLIENT=G.ID_CLIENT
LEFT JOIN CLIENTI_BANCA C ON I.ID_CLIENT=C.ID_CLIENT;

SELECT 
C.ID_CLIENT,
C.ID_CUTIE,
C.TIP_CUTIE,
C.VALOARE_DECLARATA,
C.SCURTA_DESCRIERE,
G.VALOARE_INDATORARE,
G.NOTA
FROM CUTIE_VALORI C
LEFT JOIN GRAD_INDATORARE G ON C.ID_CLIENT=G.ID_CLIENT;


SELECT 
AVG(VALOARE_DECLARATA) AS Valoare_medie,
SUM(VALOARE_DECLARATA) AS Valoare_totala
FROM CUTIE_VALORI;

SELECT
AVG(VALOARE_IMPRUMUT) AS SUMA_IMPRUMUTATA_IN_MEDIE,
AVG(DOBANDA) AS DOBANDA_MEDIE,
SUM(VALOARE_IMPRUMUT)AS SUMA_IMPRUMUTATA_IN_TOTAL
FROM IMPRUMUTURI;

SELECT
AVG(SALARIU) AS SALARIUL_MEDIU,
SUM(SALARIU) AS CHELTUIELI_ANUALE_CU_SALARIILE,
SUM(SALARIU)/12 AS CHELTUIELI_LUNARE_CU_SALARIILE
FROM ANGAJATI_BANCA;

SELECT 
AVG(VALOARE_SOLD)/12 AS ULTIMELE_12_RATE,
SUM(VALOARE_SOLD) AS BANI_INSTRAINATI
FROM IMPRUMUTURI;

SELECT *
FROM ANGAJATI_BANCA
WHERE POZITIE_OCUPATA LIKE 'Manag%';

SELECT *
FROM ANGAJATI_BANCA
WHERE POZITIE_OCUPATA LIKE 'Dir%';

SELECT *
FROM INVESTITII
WHERE ETICHETA_BURSA LIKE 'NASDAQ%';


SELECT*
FROM CUTIE_VALORI
WHERE SCURTA_DESCRIERE LIKE 'Bij%';

SELECT *
FROM (
SELECT 
ID_ANGAJAT,
NUME_ANGAJAT,
POZITIE_OCUPATA,
SALARIU,
ESTE_CLIENT
FROM ANGAJATI_BANCA
ORDER BY SALARIU DESC
)
WHERE ROWNUM <= (
SELECT COUNT(*) 
FROM ANGAJATI_BANCA 
WHERE SALARIU >= 5000
);

--GESTIUNEA UNOR OBIECTE DE TIP VEDERE,INDEX,SINONIM
DROP VIEW VEDERI_CLIENTI;
CREATE VIEW VEDERI_CLIENTI AS
SELECT ID_CLIENT, NUME_CLIENT, SOLD_CONT
FROM CLIENTI_BANCA
WHERE SOLD_CONT > 10000;

SELECT*FROM VEDERI_CLIENTI;

CREATE INDEX IND_NUME_CLIENT ON CLIENTI_BANCA(NUME_CLIENT);
DROP INDEX IND_NUME_CLIENT;

CREATE SYNONYM CLIENTI_SIN FOR CLIENTI_BANCA;
SELECT* FROM CLIENTI_SIN;
DROP SYNONYM CLIENTI_SIN;